---
title: "Exploration"
output: html_notebook
---



Number of different owners
```{r}
tidy_whisky$owner %>%
    n_distinct()
    
```

Owners in order of capacity
```{r}
tidy_whisky %>%
    group_by(owner) %>% 
    summarise(total_capacity = sum(capacity)) %>%
    arrange(desc(total_capacity))
```

```{r}
library(ggrepel)
tidy_whisky %>%
    group_by(distillery) %>% 
    ggplot() +
    aes(reorder(distillery, -strength), strength) +
    geom_col() +
    # geom_text_repel(aes(label = distillery),
    #               box.padding   = 0.35,
    #               point.padding = 0.5,
    #               segment.color = 'grey50',
    #               size = 2) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=90, hjust=1)
  )


```

```{r}
unique(tidy_whisky[flavours])

tidy_whisky %>% 
              pivot_longer(body:floral, names_to = "flavour", values_to = "strength") %>%
            mutate(strength = reorder(strength, levels = c("smoky", "medicinal", "tobacco", "spicy", "winey", "body", "sweetness", "malty', "nutty", "honey", "fruity", "floral")))
```

```{r}

tidy_whisky <-
    read_csv("clean_data/tidy_whisky.csv")
tidy_whisky %>%
    filter(distillery == "Lagavulin" |
               distillery == "GlenGrant" |
           distillery == "Laphroaig" |
               distillery == "Ardbeg" |
    distillery == "Bowmore" |
        distillery == "Aberlour")%>%
        pivot_longer(body:floral, names_to = "flavour", values_to = "strength") %>%
    group_by(distillery, flavour) %>% 
    ggplot() +
    aes(flavour, strength) +
    geom_col() +
    # geom_text_repel(aes(label = distillery),
    #               box.padding   = 0.35,
    #               point.padding = 0.5,
    #               segment.color = 'grey50',
    #               size = 2) +
        facet_wrap(~ distillery) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=90, vjust = 0.33)
  )
```

```{r}
c("malty", "sweetness", "nutty")

c("smoky", "medicinal", "tobacco")

c("honey", "floral", "fruity", "spicy") < 2
c("honey", "floral", "fruity", "spicy") > 2

tidy_whisky %>%
    group_by(distillery) %>% 
    mutate(richness = sum(c(floral,malty)))

body interaction
```

```{r}
tidy_whisky %>%
    # group_by(distillery) %>%
    # mutate(richness = sum(body:floral)-smoky) %>%
        mutate(richness = rowSums(.[9:17] < 0)) %>% 
    ggplot() +
    aes(richness, smoky + medicinal, colour = region) +
    geom_point() +
    geom_jitter() +
  geom_text_repel(aes(label = distillery),
                  # box.padding   = 0.35, 
                  # point.padding = 0.5,
                  # segment.color = 'grey50',
                  size = 2) +
  theme(legend.position = "bottom")
# xlim(25, 80) +
#   ylim(0, 50)
```

```{r}
tidy_whisky %>% 
    filter(smoky == min(smoky))

max(tidy_whisky$winey)
```

